### ISSUE TITLE
Zend\Json\Json::decode null or empty string throw Zend\Json\Exception\RuntimeException on PHP7

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-json#6]
Similar to https://github.com/zendframework/zf1/issues/678. ZF1 fix PR on https://github.com/zendframework/zf1/pull/680.

---

Originally posted by @yuripave at https://github.com/zendframework/zend-json/issues/23

**Comment by weierophinney** [comment]
As already told in zendframework/zend-cache#95
- It's a bug in zend-cache that will be addressed by zendframework/zend-cache#96
- In my opinion a serializer (all of `zend-serializer` and `zend-json`) should throw an exception in case of trying to unserialize or decode invalid input


---

Originally posted by @marc-mabe at https://github.com/zendframework/zend-json/issues/23#issuecomment-210607702

**Comment by weierophinney** [comment]
Agree as a serializer component we should throw an exception in case of trying to unserialize or decode invalid input.
Those that upgrading PHP5 to PHP7 will need to deal with `json_last_error` behavior change such that  `json_decode('')` PHP5 return `JSON_ERROR_NONE` but PHP7 return `JSON_ERROR_SYNTAX`.

References:
https://bugs.php.net/bug.php?id=71718
http://php.net/manual/en/function.json-last-error.php#118165
http://stackoverflow.com/questions/36362856/php7-json-and-zend-decoding-failed-syntax-error


---

Originally posted by @yuripave at https://github.com/zendframework/zend-json/issues/23#issuecomment-210736544

**Comment by weierophinney** [comment]
Php changed behavior of `json_last_error` with major version changing. Component `zend-json` doesn't change major or even minor version. In my opinion, it must preserve backward compatibility and fix issue on php7. Anyway, component should have the same behaviour on all supported versions of php.


---

Originally posted by @v-noskov at https://github.com/zendframework/zend-json/issues/23#issuecomment-210760438

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)

**Comment by cline-pk** [comment]
```
function utf8_json_encode($array, $key = null)
{
    if (is_array($array)) {
        foreach ($array as $key => $value) {
            $array[$key] = utf8_json_encode($value, $key); //recursive
        }
    } elseif (is_string($array)) {
        $fixed = mb_convert_encoding($array, "UTF-8", "UTF-8");
        return $fixed;
    }
    return json_encode($array);
	
}

function utf8_json_decode($json) {
	
	$res = json_decode(preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $json), true);
	return $res;
	
}


```
